name: job_tracker_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  flutter_remix: ^0.0.3
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  flutter_html: ^3.0.0
  fl_chart: ^1.0.0
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - .env
